[Mon Dec 10 23:15:04.892498 2018] [php7:warn] [pid 41888] [client 127.0.0.1:54410] PHP Warning:  session_start(): open(/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/session//sess_5b3f8a594ae948f8d987bc5c420be825, O_RDWR) failed: Permission denied (13) in /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/session/Session.php on line 36
[Mon Dec 10 23:15:04.893682 2018] [php7:warn] [pid 41888] [client 127.0.0.1:54410] PHP Warning:  session_start(): Failed to read session data: files (path: /Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/session/) in /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/session/Session.php on line 36
[Mon Dec 10 23:15:05.176259 2018] [php7:error] [pid 41888] [client 127.0.0.1:54410] PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/runtime/cache/63). in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/twig/twig/lib/Twig/Environment.php(369): Twig_Cache_Filesystem->write('/Applications/X...', '<?php\\n\\n/* Index...')\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Environment->loadTemplate('Index/index.pht...')\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/Twig.php(62): Twig_Environment->render('Index/index.pht...', Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/apps/Web/controllers/IndexController.php(24): System\\Twig->load()\n#4 /Applications/XAMPP/xamppfiles/htdocs/friends/system/org/IocInjection.php(31): Web\\IndexController->index(Object(Illuminate\\Http\\Request))\n#5 /Applications/XAMPP/xamppfiles/htdocs/friends/syste in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 55
[Mon Dec 10 23:15:05.202759 2018] [php7:error] [pid 41888] [client 127.0.0.1:54410] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/runtime/logs/error.log" could not be opened: failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, 'error', Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/LogMsg.php(98): Monolog\\Logger->error('error', Array)\n#4 [internal function]: System\\LogMsg::_rare_shutdown_catch_error()\n#5 {main}\n  thrown in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Mon Dec 10 23:15:05.958860 2018] [php7:warn] [pid 41888] [client 127.0.0.1:54410] PHP Warning:  session_start(): open(/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/session//sess_5b3f8a594ae948f8d987bc5c420be825, O_RDWR) failed: Permission denied (13) in /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/session/Session.php on line 36
[Mon Dec 10 23:15:05.959154 2018] [php7:warn] [pid 41888] [client 127.0.0.1:54410] PHP Warning:  session_start(): Failed to read session data: files (path: /Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/session/) in /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/session/Session.php on line 36
[Mon Dec 10 23:15:05.989686 2018] [php7:error] [pid 41888] [client 127.0.0.1:54410] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/runtime/logs/access.log" could not be opened: failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, 'access', Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/LogMsg.php(131): Monolog\\Logger->error('access', Array)\n#4 /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/macaw/Macaw.php(169): System\\LogM in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Mon Dec 10 23:15:05.990643 2018] [php7:error] [pid 41888] [client 127.0.0.1:54410] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/Applications/XAMPP/xamppfiles/htdocs/friends/public/../resources/runtime/logs/error.log" could not be opened: failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, 'error', Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/system/base/LogMsg.php(98): Monolog\\Logger->error('error', Array)\n#4 [internal function]: System\\LogMsg::_rare_shutdown_catch_error()\n#5 {main}\n  thrown in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Thu Dec 27 11:32:34.560970 2018] [php7:error] [pid 15785] [client 127.0.0.1:53831] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Operation timed out in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php:68\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(68): PDO->__construct('mysql:host=182....', 'root', 'jia980709', Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=182....', 'root', 'jia980709', Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=182....', Array, Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFa in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connection.php on line 664
[Thu Dec 27 11:34:05.349286 2018] [php7:error] [pid 16207] [client 127.0.0.1:53932] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Operation timed out in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php:68\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(68): PDO->__construct('mysql:host=182....', 'root', 'jia980709', Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=182....', 'root', 'jia980709', Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=182....', Array, Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFa in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connection.php on line 664
[Thu Dec 27 11:35:12.876113 2018] [php7:error] [pid 15777] [client 127.0.0.1:54026] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Operation timed out in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php:68\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(68): PDO->__construct('mysql:host=182....', 'root', 'jia980709', Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=182....', 'root', 'jia980709', Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=182....', Array, Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFa in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Connection.php on line 664
[Thu Dec 27 11:35:28.094006 2018] [php7:warn] [pid 15766] [client 127.0.0.1:54095] PHP Warning:  Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Builder.php on line 859
[Thu Dec 27 11:35:28.095053 2018] [php7:error] [pid 15766] [client 127.0.0.1:54095] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Database\\Grammar::parameterize() must be of the type array, string given, called in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php on line 254 and defined in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Grammar.php:138\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php(254): Illuminate\\Database\\Grammar->parameterize('=')\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php(200): Illuminate\\Database\\Query\\Grammars\\Grammar->whereIn(Object(Illuminate\\Database\\Query\\Builder), Array)\n#2 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Array, 0)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/support/Collection.php(932): array_map(Object(Closure), Array, Array)\n#4 /Applications/XAMPP/xamppfile in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Grammar.php on line 138
[Thu Dec 27 11:35:33.441732 2018] [php7:warn] [pid 15580] [client 127.0.0.1:54102] PHP Warning:  Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Builder.php on line 859
[Thu Dec 27 11:35:33.442250 2018] [php7:error] [pid 15580] [client 127.0.0.1:54102] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Database\\Grammar::parameterize() must be of the type array, string given, called in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php on line 254 and defined in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Grammar.php:138\nStack trace:\n#0 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php(254): Illuminate\\Database\\Grammar->parameterize('=')\n#1 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Query/Grammars/Grammar.php(200): Illuminate\\Database\\Query\\Grammars\\Grammar->whereIn(Object(Illuminate\\Database\\Query\\Builder), Array)\n#2 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Array, 0)\n#3 /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/support/Collection.php(932): array_map(Object(Closure), Array, Array)\n#4 /Applications/XAMPP/xamppfile in /Applications/XAMPP/xamppfiles/htdocs/friends/vendor/illuminate/database/Grammar.php on line 138
